### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by idanka** [satoshiiizuka/siggraphasia2019_remastering#2]
Hi!
What could be the cause of the error?

#python remaster.py --input elefant.mp4 --gpu --disable_colorization

Traceback (most recent call last):
  File "remaster.py", line 17, in <module>
    from torchvision import transforms
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/home/dankahazi/anaconda3/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/home/dankahazi/anaconda3/lib/python3.7/site-packages/PIL/__init__.py)

**Comment by idanka** [comment]
or use "conda install pytorch torchvision cudatoolkit=10.1 -c pytorch"

# python remaster.py --input elefant.mp4 --gpu --disable_colorization
Traceback (most recent call last):
  File "remaster.py", line 19, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
